urls:
  iroqwa_http:
    url: http://github.com/
    code: 301
    headers:
      Location: https://github.com/
  iroqwa_https:
    url: https://github.com/
    code: 200
    headers:
      Server: GitHub.com
    noheaders:
      X-Cache: none
    body: "<html"
    nobody: "Hacked"
  iroqwa_notfound:
    url: https://github.com/nonexistent-7570-5022-4567
    code: 404
