name: Go
on: [push]
permissions: read-all
jobs:

  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      id: go

    - name: Version
      run: go version

    - name: Build
      run: go build -v .

    - name: Test
      run: ./headerscheck -debug
